// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"MakeAppointmentMOBILEHUB","alias":"$LATEST","description":"Bot to book a dentist appointment.","bot-template":"bot-appointments","commands-help":["I would like to book an appointment","Book an appointment","I would like to see the dentist","I would like to schedule a visit","Make appointment"],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-east-1:a5fdf7eb-76a1-45bd-a107-6735867a4169',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'kinesis-hosting-mobilehub-946153654',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2frsvw7o0dns5.cloudfront.net',
    'aws_mobile_analytics_app_id': 'b6a9987c07ba49558d60d747a034fc8a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7e088c99-b8a3-4e93-bb80-449a4a5224c9',
    'aws_project_name': 'Kinesis',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'kinesis-mobilehub-946153654',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'kinesis-userfiles-mobilehub-946153654',
    'aws_user_files_s3_bucket_region': 'us-east-1',
}

export default awsmobile;
